# Generated by Django 4.0.3 on 2022-03-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likeCount',
            new_name='likesCount',
        ),
    ]
